### ISSUE TITLE
Henry's code review.

### ISSUE THREAD

**Issue by prashant-r** [prashant-r/Database-Systems#10]
Any feedback on code, notice of tests failing on dry runs, enhancements or general refactoring suggestions. Seeking your approval of this code for submission.

**Comment by henryjonesj** [comment]
Cross check the hashNext() function with the prefetch. Essentially there are many conditions that are handled in devesh's code.

Also , in the restart method of HashJoin.Java, shouldn't both A and B references of the scan be restarted?

and i noticed that the array index out of bounds exception is something that has to be noted as well. If you check in his code, he has initialized the matching tuples as an array, we have as a list.

probably some where we are trying to access it out of bounds.

Also noticed, the very first time, intelliJ is started and the code is executed, test cases passes. If it is run the second time, is when the exceptions started appearing. So there can be chances of something not being reset properly, or closed properly.

And more thing,  I tested the data set ( department table and employee table) with some more additional rows, ran the test cases and manually verified them. Just to ensure that we don't miss out on any corner scenario. U can test if you have edge test cases as well. God Speed :)

**Comment by prashant-r** [comment]
Thanks will look into it now..

**Comment by prashant-r** [comment]
Fixed.
